### ISSUE TITLE
make npm link work better

### ISSUE THREAD

**Issue by nicksellen** [yunity/yunity-setup#1]
Currently running sudo npm link causes some problems for some peoples setups. We can just make a symlink manually between the two projects I think.

**Comment by raphaelfellmer** [comment]
sounds good from our point of view but you should consider Velato elastic search database parameters setting as well (martin and raphael ;-)

**Comment by nicksellen** [comment]
I made it do symlinks directly now...

see https://github.com/yunity/yunity-setup/commit/d654fedc64479bfff8e5e366a53be279343b4d3c
