### ISSUE TITLE
Setup on Ubuntu 15.10

### ISSUE THREAD

**Issue by stefaneidelloth** [yunity/yunity-setup#12]
Hello I tried to follow the system setup on Ubuntu 15.10
I am not so familar with linux and I am wondering If I should be able to skip the commands in the section
"postgresql 9.4 in Ubuntu 14.04 and lower" 
completely or If I should execute some alternative commands for Ubuntu 15.10?

If I skip the section I get the output below and I guess that postgres is not yet installed correctly.

**Edit**
I found another setup description that seems to be more detailed. Maybe it would be better if
the github site only contains a link to the wiki:
https://yunity.atlassian.net/wiki/display/YUN/Application+Setup
The section "Extra steps you might need..." was very helpful for me. 

I also suggest to include an instruction on how to install pm2:
sudo npm install pm2 -g

---

```
psql: FATAL:  Peer authentication failed for user "postgres"
psql: FATAL:  Peer authentication failed for user "postgres"
--> failed to create db user yunity-user, please set pg_user or pg in local_settings.make or ensure the default 'postgres' db role is available
psql: FATAL:  Peer authentication failed for user "postgres"
createdb: could not connect to database template1: FATAL:  Peer authentication failed for user "postgres"
--> failed to create db user yunity-user, please set pg_user or pg in local_settings.make or ensure the default 'postgres' db role is available
```

(edited to use nice formatted box, and remove extraneous output)

**Comment by nicksellen** [comment]
Yeah, thanks :)

It should indeed point to the wiki a bit more. I mentioned it on #11.

https://yunity.atlassian.net/wiki/pages/viewpage.action?pageId=16187483 seems quite clear that it really means 14.04 and lower, so you should be good!

The setup script will install pm2.

Is anything still not working?

**Comment by stefaneidelloth** [comment]
> seems quite clear that it really means 14.04 and lower

Yes, at the atlassian wiki page is clearer. 

> The setup script will install pm2.

I see. The make failed for me in the first attempt and afterwards I tried to run a pm2 command that failed, too. Therefore I thought the pm2 dependency would be missing. If the previous make step installs it its just fine.
