### ISSUE TITLE
Make postgres setup JustWork

### ISSUE THREAD

**Issue by nicksellen** [yunity/yunity-setup#8]
At the moment it requires you to set `pg` in `local_settings.make` if your system requires `sudo -u postgres` before pg commands (e.g. `psql`).

It would be nicer if it just worked.

**Comment by tiltec** [comment]
Is this still open @nicksellen ?

**Comment by nicksellen** [comment]
It's still open in that it's not done, I just made a much clearer note here https://yunity.atlassian.net/wiki/display/YUN/Application+Setup.

It would be nice still. It's not high priority for me though.

I'll close it, and we can address it if somebody complains :)
