### ISSUE TITLE
Create better instruction for setup for different Ubuntu 14.0 and Mac

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity-setup#9]
Asked by Raphael F. in Trello

**Comment by nicksellen** [comment]
I've created more OS specific instructions on https://yunity.atlassian.net/wiki/display/YUN/System+Setup

The OSX one needs a bit of love from someone that has a mac. Currently Curtis is the only one that seems to be using a mac for now.

I'm installing an Ubuntu 15.04 VM to check setup instructions, and will also do a 14.10 one too.
